root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata"]
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
time = false

[server]
manual_restart = false
kill_delay = 500
stop_on_error = true